### Create new user
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "Luca Doe",
  "email": "high@email.com",
  "role": "admin"
}

### List all users
GET http://localhost:5000/users

### List one user
GET http://localhost:5000/users/7740b31d-0365-4a2a-bda5-45c519980ded

### Update user
PUT http://localhost:5000/users/7740b31d-0365-4a2a-bda5-45c519980ded
Content-Type: application/json

{
  "name": "John Doe",
  "role": "admin"
}

### Delete user
DELETE http://localhost:5000/users/ca89f7cf-eba0-46e7-bbc5-f382802fd936


### 404 Route
GET http://localhost:5000/user/
